"""Read-only access to the persisted v2/v3 promotion reports."""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict

import pandas as pd


class ComparisonReportError(RuntimeError):
    """Raised when the persisted comparison report is missing or invalid."""


@dataclass(frozen=True)
class ComparisonReport:
    scenarios: pd.DataFrame
    cost_sensitivity: pd.DataFrame
    decision: Dict[str, Any]


class ModelComparisonDataProvider:
    """Load the reproducible outputs generated by the promotion pipeline."""

    REQUIRED_SCENARIO_COLUMNS = {
        "model_version", "scenario", "threshold", "precision", "recall", "f1",
        "roc_auc", "pr_auc", "brier_score", "log_loss", "tn", "fp", "fn", "tp",
        "campaign_rate", "churn_coverage", "relative_cost", "predict_time",
    }
    REQUIRED_SENSITIVITY_COLUMNS = {
        "fn_fp_ratio", "best_threshold", "precision", "recall", "cost",
        "predicted_positive_rate",
    }

    def __init__(self, report_dir=None):
        project_root = Path(__file__).resolve().parents[3]
        self.report_dir = Path(report_dir) if report_dir else project_root / "reports" / "promotion"

    def load(self) -> ComparisonReport:
        scenarios = self._read_csv("promotion_comparison.csv")
        sensitivity = self._read_csv("cost_sensitivity.csv")
        decision = self._read_json("promotion_decision.json")
        self._require_columns(scenarios, self.REQUIRED_SCENARIO_COLUMNS, "promotion_comparison.csv")
        self._require_columns(sensitivity, self.REQUIRED_SENSITIVITY_COLUMNS, "cost_sensitivity.csv")
        if "champion" not in decision.get("metrics", {}) or "challenger" not in decision.get("metrics", {}):
            raise ComparisonReportError("promotion_decision.json has no champion/challenger metrics")
        return ComparisonReport(scenarios=scenarios, cost_sensitivity=sensitivity, decision=decision)

    def _read_csv(self, name):
        path = self.report_dir / name
        try:
            return pd.read_csv(path)
        except (OSError, pd.errors.ParserError) as exc:
            raise ComparisonReportError("Could not load {}".format(path)) from exc

    def _read_json(self, name):
        path = self.report_dir / name
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise ComparisonReportError("Could not load {}".format(path)) from exc

    @staticmethod
    def _require_columns(frame, required, name):
        missing = required.difference(frame.columns)
        if missing:
            raise ComparisonReportError("{} is missing columns: {}".format(name, ", ".join(sorted(missing))))
